### ISSUE TITLE
Encountered an issue with transfer pretrained normative models on my own data.

### ISSUE THREAD

**Issue by NStaalstra** [predictive-clinical-neuroscience/PCNtoolkit-demo#17]
Dear PCNtoolkit team,

I am trying to apply your normative modelling approach to my data on AB depositions in Alzheimer patients. I followed your tutorials (BLR_normativemodel.., visualizations and now transfer_pretrained_normative_model) and trained a BLR model. I have encountered an issue stating that the nm.blr.warp object has no attribute 'get_n_params'. I have tried to delve in your scripts but I can't find the issue.

The full error: 
AttributeError                            Traceback (most recent call last)
Cell In[12], line 29
     27 # get the warp and warp parameters
     28 W = nm.blr.warp
---> 29 warp_param = nm.blr.hyp[1:nm.blr.warp.get_n_params()+1] 
     31 # first, we warp predictions for the true data and compute evaluation metrics
     32 med_te = W.warp_predictions(np.squeeze(yhat_te), np.squeeze(s2_te), warp_param)[0]

AttributeError: 'NoneType' object has no attribute 'get_n_params'

Thanks in advance!

Nick

**Comment by AuguB** [comment]
Hi Nick,

I think this was an issue before, and it was solved here:

https://github.com/predictive-clinical-neuroscience/PCNtoolkit-demo/issues/13#issuecomment-2830493785

Sorry that that's hidden, it should be a separate issue. 

Stijn

**Comment by NStaalstra** [comment]
Hi Stijn,

I tried this is all (three?) predict calls till the problem occurs. I tried to update to the last version of the toolkit but it still gives the same error.

Nick

**Comment by NStaalstra** [comment]
Hi Stijn,

I thought maybe the trained model did not include a warp. I loaded the pkl file, which returned None after printing the warp.
So, I added  warping= 'WarpSinArcsinh' or 'sinarcsinh' to the estimate() call. But this did not fix the issue either.
Do you know if I can try anything else?

Nick

**Comment by NStaalstra** [comment]
Hi Stijn,

I found the solution to my issue, the warp='WarpSinArcsinh' also needed to be in the estimate function in the script for creating the model. This fixed my issues.

thx,

Nick

**Comment by AuguB** [comment]
Hi Nick, sorry for the late response. Glad you figured it out 👍
